sixad/sixad usr/bin/

sixad/bins/hidraw-dump usr/sbin/
sixad/bins/sixpair usr/sbin/
sixad/bins/sixpair-kbd usr/sbin/
sixad/bins/sixad-raw usr/sbin/
sixad/bins/sixad-bin usr/sbin/
sixad/bins/sixad-uinput-sixaxis usr/sbin/

sixad/hcid/hcid usr/sbin/

sixad/98-sixad.rules lib/udev/rules.d/

#sixad/x11-sony-keypad.fdi usr/share/hal/fdi/policy/20thirdparty/

sixad/default/sixad etc/default/
sixad/init/sixad etc/init.d/

sixad/mans/* usr/share/man/man1/
