#!/bin/bash

set -e

#DEBHELPER#

case "$1" in
  remove)
update-rc.d -f sixad remove
if [ -f /var/lib/sixad/10-joystick.conf.bak ]; then
mv /var/lib/sixad/10-joystick.conf.bak /usr/lib/X11/xorg.conf.d/10-joystick.conf
fi
  ;;
  purge)
update-rc.d -f sixad remove
if [ -f /var/lib/sixad/10-joystick.conf.bak ]; then
mv /var/lib/sixad/10-joystick.conf.bak /usr/lib/X11/xorg.conf.d/10-joystick.conf
fi
rm -rf /var/lib/sixad/
  ;;
esac

