#!/bin/bash

#Small script to install additional binaries

ARCH=`uname -m`

case $ARCH in
    powerpc|ppc|powerpc64|ppc64)
cp compat/hcid_powerpc bins/hcid
cp compat/libbluetooth.so.2_powerpc bins/libbluetooth.so.2
  ;;
    amd64|x64|x86_64)
cp compat/hcid_amd64 bins/hcid
cp compat/libbluetooth.so.2_amd64 bins/libbluetooth.so.2
  ;;
    *)
cp compat/hcid_i386 bins/hcid
cp compat/libbluetooth.so.2_i386 bins/libbluetooth.so.2
  ;;
esac
