.\" Help file created by falkTX
.TH SIXAD-UINPUT-SIXAXIS "1" "November 2009" "sixad-uinput-sixaxis "User Commands"
.SH NAME
sixad-uinput-sixaxis
.SH SYNOPSIS
.B sixad-uinput-sixaxis
.SH NOTICE
sixad-uinput-sixaxis is part of the sixad driver and it's only used when needed.

To use the sixad driver, please run "sixad".
